services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:test
    container_name: medusa-server
    depends_on:
      - postgres
      - redis
    ports: 
      - "9000:9000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/medusa-docker
      REDIS_URL: redis://cache
      NODE_ENV: development
      JWT_SECRET: some_jwt_secret
      COOKIE_SECRET: some_cookie_secret
      PORT: 9000
    command: ["develop"]

  postgres:
    image: postgres:10.4
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-docker

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  storefront:
    build:
      context: ./storefront
      dockerfile: Dockerfile
    image: storefront:test
    container_name: medusa-storefront
    depends_on:
      - backend
    ports:
      - "8000:8000"
    env_file:
      - ./storefront/.env.local
